### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED error when running yarn start

### ISSUE THREAD

**Issue by Brentably** [blocknative/react-demo#253]
This is the full error I'm getting....

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:412:16)
    at handleParseError (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:463:10)
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:495:5
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:354:12
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:412:16)
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:444:10
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/webpack/lib/NormalModule.js:320:13
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/brent/Desktop/IAMSOLIDITYDEV/react-demo/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Adamj1232** [comment]
@Brentably is this issue still presenting?

**Comment by Brentably** [comment]
Uhhh, I ended up downloading the latest LTS version of node and finding some hacky command to add to the node start script that ended up fixing it... I deleted the repo otherwise I'd go and cite the specific command

**Comment by Brentably** [comment]
by command I mean a flag of some sort. --do-it-this-way

**Comment by Adamj1232** [comment]
Great, glad you got it working. Will close for now. Thanks again!
