### ISSUE TITLE
WebSocket not present in global scope and no wsConstructor option was provided.

### ISSUE THREAD

**Issue by Mehranh** [blocknative/react-demo#31]
Hi 

I installed bnc-notify 1.5.0 in my NodeJs app,
It took an error that you can see below on initial line
`notify =  Notify(options);`
```
Error: WebSocket not present in global scope and no wsConstructor option was provided.
    at new SturdyWebSocket (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:534:1363)
    at new Blocknative (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:2305:4758)
    at init$1 (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:3650:2274)
```
``

Could you please help us to resolve this?

Thanks

**Comment by aaronbarnardsound** [comment]
Hey Mehranh, I am going to close this issue as this repo is for the demo app and isn't relevant to the issue you are describing. I would encourage you to create an issue on the [SDK repo](https://github.com/blocknative/sdk) if you are still having trouble.
